alwadi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('alwaditravel.urls'))
]

alwaditravel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path


from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('appointment/<pk>/detail', AppointmentDetail.as_view(), name='appointment-detail'),
    path('appointment/make', AppointmentMake.as_view(), name='appointment-make'),

]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alwaditravel/models.py
from datetime import datetime
from django.core.exceptions import ValidationError

from django.db import models

def validate_file_size(value):
    filesize= value.size

    if filesize > 262144:
        raise ValidationError("The maximum file size that can be uploaded is 256kb")
    else:
        return value
# Create your models here.
class Appointment(models.Model):
    first_name = models.CharField(max_length=30, blank=False, null=False)
    second_name = models.CharField(max_length=30, blank=False, null=False)
    last_name = models.CharField(max_length=30, blank=False, null=False)
    other_name = models.CharField(max_length=30, blank=False, null=False)
    passport_number = models.CharField(max_length=30, blank=False, null=False)
    passport_copy = models.ImageField(upload_to='uploads', validators=[validate_file_size])
    invitation_letter = models.FileField(upload_to='uploads',validators=[validate_file_size])
    apt_date = models.DateField(verbose_name="Appointment Date")
    queue_number = models.IntegerField(default=-1)

    def FullName(self):
        return str(self.first_name + " " + self.second_name + " " + self.last_name)

    def __str__(self):
        """String for representing the Model object."""
        return str(self.first_name + " " + self.second_name)


class AppointmentSetting(models.Model):
    apt_date = models.DateField()
    apt_limit = models.IntegerField(blank=False, null=False, default=50)

    def __str__(self):
        """String for representing the Model object."""
        return str(self.apt_date)


class Holidays(models.Model):
    name = models.CharField(max_length=60)
    h_date = models.DateField()

    def __str__(self):
        """String for representing the Model object."""
        return str(self.name)

alwaditravel/forms.py
from django import forms
from .models import *


class AppointmentMakeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AppointmentMakeForm, self).__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].widget.attrs['class'] = 'form-control'
            if f == 'apt_date':
                self.fields[f].widget.attrs['autocomplete'] = 'off'

    # def clean_files(self):
    #     data = self.cleaned_data['passport_copy', 'invitation_letter']
    #     print(data)
    #     if data[1] and data[2]:
    #         if data1.size > 0.25*1024*1024 or data1.size > 0.25*1024*1024:
    #             raise forms.ValidationError("File Size too large ( > 256kb ), must be less than 256kb")
    #         return data
    #     else:
    #         raise forms.ValidationError("Couldn't read uploaded image")
    

    # def clean_field(self):
    #     print('it is working')
    #     image = self.cleaned_data.get('passport_copy', False)
    #     if image:
    #         if image.size > 0.25*1024*1024:
    #             raise ValidationError("Image file too large ( > 256kb )")
    #         return image
    #     else:
    #         raise ValidationError("Couldn't read uploaded image")

    class Meta:
        model = Appointment
        fields = "__all__"
        widgets = {
            'queue_number': forms.HiddenInput(),

        }


class AppointmentDetailForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AppointmentDetailForm, self).__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Appointment
        fields = "__all__"

alwaditravel/views.py
from django.contrib.messages.views import SuccessMessageMixin

from django.shortcuts import render
from django.http.response import HttpResponseRedirect, Http404

from django.views.generic import *
from .forms import *
from django.contrib import messages


def home(request, lng="ar"):
    return render(request, template_name='alwaditravel/index.html', context={"lng": lng, "current_url_name": "home"})


# checks if the view is refered from another view
def get_referer(request):
    referer = request.META.get('HTTP_REFERER')
    if not referer:
        return None
    return referer


class AppointmentMake(CreateView, SuccessMessageMixin):
    model = Appointment
    form_class = AppointmentMakeForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        h = Holidays.objects.all().values('h_date')
        c = AppointmentSetting.objects.filter(apt_limit=0).values('apt_date')

        context['holidays'] = h
        context['apt_count'] = c
        a_form = ['الاسم الأول', 'اسم الأب', 'اسم الجد', 'اسم العائلة', 'رقم جواز السفر', 'صورة جواز السفر',
                             'مستند تأشيرة', 'تاريخ الموعد','']
        context['gg'] = zip(self.get_form(), a_form)
        return context

    def form_valid(self, form):

        # clean the data

        data = form.cleaned_data

        # check the existing AppointmentSetting object
        apt_Setting_exist = AppointmentSetting.objects.filter(apt_date=data.get("apt_date"))

        apt_setting_obj = None
        if (len(apt_Setting_exist) > 0):  # load appointment setting object
            apt_setting_obj = apt_Setting_exist[0]
        else:  # create new setting object
            apt_setting_obj = AppointmentSetting.objects.create(apt_date=data.get("apt_date"))

        booked_today = Appointment.objects.filter(passport_number=data.get("passport_number"),
                                                  apt_date=data.get("apt_date")).exists()

        if (booked_today):
            messages.error(self.request, message="You can not Book twice per day")

            return HttpResponseRedirect("/appointment/make")
        # maximum limit reached
        if (apt_setting_obj.apt_limit <= 0):
            messages.error(self.request, message="Appointment for the selected date is full")
            return HttpResponseRedirect("/appointment/make")

        # save form
        self.object = form.save()

        # update and save appontment setting object
        apt_setting_obj.apt_limit -= 1
        apt_setting_obj.save()

        # update the queue number
        self.object.queue_number = 50 - apt_setting_obj.apt_limit
        self.object.save()

        messages.success(self.request, "Your Appointment is Booked Successfully !")
        return HttpResponseRedirect('/appointment/' + str(self.object.id) + '/detail')


class AppointmentDetail(DetailView):
    model = Appointment
    form_class = AppointmentDetailForm

    def get(self, request, *args, **kwargs):
        if not get_referer(self.request):
            return HttpResponseRedirect('/')

        self.object = self.get_object()
        context = self.get_context_data(object=self.object)

        return self.render_to_response(context)

alwaditravel/templates/alwaditravel/appointment_detail.html
{% extends "alwaditravel/base.html" %}

{% load static %}
{% block content %}


<div class="container p-5" id="content">

    <div class="p-3 bg-danger text-white rounded text-center print-no">
        <h2>Appointment Detail</h2>
    </div>

    <table class="table table-borderless mb-3">
        <tr>
            <td>
                &nbsp;
            </td>
            <td align="center" rowspan="2">

                <img alt="Alwadi Logo" src="{% static 'alwaditravel/img/logo.png' %} loading="lazy""
                     width="15%" class="d_logo">

            </td>
            <td align="right">
                &nbsp;
            </td>
        </tr>


    </table>

    <table class="table table-borderless fw-bolder">

        <tr>
            <td>
                Queue Number : {{object.queue_number}} <br><span class="fw-bold" style="font-family: Tajawal">رقم قائمة الانتظار</span>
            </td>

            <td align="right">
                Appointment Number : {{object.id}} <br><span class="fw-bold" style="font-family: Tajawal"> رقم الهوية للموعد</span>
            </td>
        </tr>
    </table>

    <hr class="bg-dark border-2 border-top border-dark w-100 m-auto "/>
    <hr class="bg-dark border-2 border-top border-dark w-100 m-auto "/>
    <table class="table table-borderless my-3">

        <tr>
            <td>
                Full Name : <span class="fw-bold" style="font-family: Tajawal">الاسم الكامل</span>
            </td>
            <td>
                <input class="form-control " disabled value="{{object.FullName}}"/>
            </td>
        </tr>
        <tr>
            <td>
                Other Name : <span class="fw-bold" style="font-family: Tajawal">اسم العائلة</span>
            </td>
            <td>
                <input class="form-control " disabled value="{{object.other_name}}"/>

            </td>

        </tr>
        <tr>
            <td>
                Passport Number : <span class="fw-bold" style="font-family: Tajawal">رقم جواز السفر</span>
            </td>
            <td>
                <input class="form-control " disabled value="{{object.passport_number}}"/>

            </td>

        </tr>
        <tr>
            <td>
                Appointment Date :<span class="fw-bold" style="font-family: Tajawal"> تاريخ الموعد</span>
            </td>
            <td>
                <input class="form-control " disabled value="{{object.apt_date}}"/>

            </td>

        </tr>
    </table>

    <hr class="bg-dark border-2 border-top border-dark w-100 m-auto"/>
    <div class="fs-5">
        <h3 class="mt-2">Remarks</h3>
        <ul>
            <li>A certificate of proof of lineage certified by the Eritrean Foreign Ministry or the
                Saudi Foreign Ministry, such as (marriage contract, birth certificate, deed proving
                lineage from the court)
            </li>
            <li>Passport copy of the traveler
            </li>
            <li>A copy of the entry stamp for non-Eritreans
            </li>
            <li>Original passport valid for more than six months
            </li>
            <li>Renewed or extended passport is accepted
            </li>
        </ul>
        <div class="fw-bold fs-5" dir="rtl" style="font-family: Tajawal;">
            <h3 class="mt-2">ملاحظات</h3>
            <ul>
                <li>
                    شهادة اثبات نسب مصدقة من الخاارجية الارترية او الخارجية السعودية مثل (عقد زواج شهادة ميلاد صك اثبات
                    نسب من المحكمة)

                </li>
                <li>صورة جواز السفر للمسافر
                </li>
                <li>صورة ختم الدخول لغير الإرتريين
                </li>
                <li>أصل الجواز ساري الصلاحية أكثر من ستة أشهر
                </li>
                <li>يتم قبول جواز السفر المتجد</li>
            </ul>

        </div>


    </div>
    <hr class="bg-dark border-2 border-top border-dark w-100 m-auto"/>
</div>

<div class="col text-center mt-2 mb-5 print-no">

    <a class="btn btn-outline-secondary mt-2 w-25 "
       href="{% url 'home' %}">
        Home</a>
    <button class="btn bg-danger mt-2 w-25 text-white" onclick="printDocument('content')">
        <i class="fas fa-pdf"></i>Print
    </button>

</div>

{% include 'alwaditravel/messages.html' %}
{% endblock %}

{% block script%}

<script>
    function printDocument(divName) {
        var printContents = document.getElementById(divName).innerHTML;
        var originalContents = document.body.innerHTML;

        document.body.innerHTML = printContents;

        window.print();

        document.body.innerHTML = originalContents;



}


</script>

{% endblock %}

alwaditravel/templates/alwaditravel/appointment_form.html
{% extends "alwaditravel/base.html" %}
{%block title%}
Make Appointment
{%endblock%}
{% block content %}
<div class="container px-4 py-4 ">
    <div class="mt-3 mb-5 p-3 bg-danger text-white rounded text-center">
        <h2>Appointment Form</h2>
    </div>
    {% if form.errors|striptags %}
    <div class="alert alert-danger" role="alert">
        {{form.errors}}
    </div>
    {% endif %}

    <div class="row mb-3">

        <div class="col-lg-8">
            <div class="col">
                <div class="card mb-2">
                    <div class="card-header py-2">
                        <p class=" m-0 fw-bolder d-flex justify-content-between"><span>Appointment</span><span> حجز الموعد</span></p>
                    </div>
                    <div class="card-body small" id="box">
                        <form action="{% url 'appointment-make' %}" enctype="multipart/form-data" method="POST"
                              onsubmit="validate(this)">
                            {% csrf_token %}
                            <div class="row">
                                {% for field, a_field in gg %}
                                {% if forloop.counter0|divisibleby:4 %}
                                {% if forloop.counter0 == 0 %}
                                <div class="col-md-6">
                                    {% else %}
                                </div>
                                <div class="col-md-6">
                                    {% endif %}
                                    {% endif %}
                                    {% if field.label != 'Queue number' %}
                                    <div class="form-group my-1 "><label class="d-flex mb-1 justify-content-between">
                                        <strong><span>{{field.label}}</span></strong><strong><span>{{a_field}}</span></strong></label>
                                        {% endif %}
                                        {{field}}
                                    </div>
                                    {% endfor %}
                                </div>


                                <div align="center" class=" mt-2 ">
                                    <button class="btn bg-warning btn-md text-white w-25" type="submit">Save</button>
                                </div>
                            </div>

                        </form>
                    </div>

                </div>
            </div>
            <div class="col-sm-4">
                <div class="card border-warning ">
                    <div class="card-header bg-danger text-white">
                        <h3 class="mt-2">Remarks</h3>
                    </div>
                    <div class="card-body">
                        <ul>
                            <li>Fill the form with care and correct information.
                            </li>
                            <li>Make an appointment for every individual.
                            </li>
                            <li>A certificate of proof of lineage certified by the Eritrean Foreign Ministry or the
                                Saudi Foreign Ministry, such as (marriage contract, birth certificate, deed proving
                                lineage from the court)
                            </li>
                            <li>Passport copy of the traveler
                            </li>
                            <li>A copy of the entry stamp for non-Eritreans
                            </li>
                            <li>Original passport valid for more than six months
                            </li>
                            <li>Renewed or extended passport is accepted
                            </li>
                        </ul>
                    </div>
                    <div class="fw-bold fs-5" dir="rtl" style="font-family: Tajawal;">
                        <h3 class="m-2">ملاحظات</h3>
                        <ul>
                            <li>املأ النموذج بعناية ومعلومات صحيحة.
                            </li>
                            <li>
                                شهادة اثبات نسب مصدقة من الخاارجية الارترية او الخارجية السعودية مثل (عقد زواج شهادة
                                ميلاد صك اثبات
                                نسب من المحكمة)

                            </li>
                            <li>صورة جواز السفر للمسافر
                            </li>
                            <li>صورة ختم الدخول لغير الإرتريين
                            </li>
                            <li>أصل الجواز ساري الصلاحية أكثر من ستة أشهر
                            </li>
                            <li>يتم قبول جواز السفر المتجدد أو المتمدد
                            </li>
                        </ul>

                    </div>


                </div>

            </div>
        </div>

    </div>
    {% include 'alwaditravel/messages.html' %}
    {% endblock %}

    {% block script %}
    <script type="text/javascript">
        var unavailableDates = [
        {% for h in holidays%}
          "{{h.h_date|date:'Y-n-j'}}",
        {% endfor %}
        {% for c in apt_count%}
          "{{c.apt_date|date:'Y-n-j'}}",
        {% endfor %}
        ];

        function nationalDays(date) {
            dmy = date.getFullYear() + "-" + (date.getMonth() + 1) + "-" + date.getDate() ;
            console.log(dmy)
            if ($.inArray(dmy, unavailableDates) == -1) {
                return [true, ""];
            } else {
                return [false, "", "Unavailable"];
            }
        }

        $(function() {
            $("#id_apt_date").datepicker({
                minDate: '0',
                dateFormat: 'yy-mm-dd',
                beforeShowDay: noWeekendsOrHolidays

            });
            $("#id_apt_date").keyup(function(){
                 $("#id_apt_date").val("");
            });

        });
            function noWeekendsOrHolidays(date) {
        var noWeekend = $.datepicker.noWeekends(date);
        if (noWeekend[0]) {
            return nationalDays(date);
        } else {
            return noWeekend;
        }
    }
    </script>


    {% endblock %}

alwaditravel/templates/alwaditravel/base.html
<!doctype html>
{% load static %}
<html lang="en">
<meta content="text/html;charset=utf-8" http-equiv="content-type"/>
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>{%block title%}{%endblock%}</title>
    <link href="index.html" rel="canonical">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'alwaditravel/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'alwaditravel/css/jquery-ui.min.css' %}" rel="stylesheet">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link crossorigin href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css2?family=Corben&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link crossorigin href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css2?family=Tajawal&display=swap" rel="stylesheet">

    <!-- Favicons -->
    <meta content="#7952b3" name="theme-color">
    <style>
        body{
        font-family: Corben;
        }
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'alwaditravel/css/print.css' %}" rel="stylesheet">
    <link href="{% static 'alwaditravel/css/carousel.css' %} " rel="stylesheet">
</head>
<body class="pt-0">
<header class="p-3 bg-light sticky print-no">
    <div class="container-fluid">
        <div class="d-flex flex-wrap align-items-center justify-content-center">
            <div class="nav-link navig col-lg-auto text-start">
                <a href="{% url 'home' %}"><img alt="Alwadi Logo" height="90px"
                                                src="{% static 'alwaditravel/img/logo.png' %}" loading="lazy"></a>
            </div>
            <ul class="nav col-12 col-lg-auto mb-2 justify-content-evenly align-items-center fw-bolder fs-5">
                {% with url_name=request.resolver_match.url_name %}
                <li class="nav-item navig">
                    <a aria-current="page" class="nav-link  text-dark {% if url_name == 'home' %}active{% endif %}"
                       href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item navig">
                    <a class="nav-link  text-dark {% if url_name == 'appointment-make' %}active{% endif %}"
                       href="{% url 'appointment-make' %}">Appointment</a>
                </li>
                <li class="nav-item navig">
                    <a class="nav-link  text-dark {% if url_name == 'appointment-make' %}disabled{% endif %}"
                       href="#services">Services</a>
                </li>
                <li class="nav-item navig">
                    <a class="nav-link  text-dark {% if url_name == 'appointment-make' %}disabled{% endif %}"
                       href="#contactus">Contact Us</a>
                </li>
                {%endwith%}
            </ul>
        </div>
    </div>
</header>
<main class="px-0">

    {% block content %}
    {% endblock %}

</main>
<div class="container border-top" id="contactus">
    <footer class="print-no mt-2">
        <div class="row">
            <div class="col text-center">
                <h5 class="fw-bold">Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a class="nav-link p-0 text-muted"
                                                 href="{%url 'home' %}">Home</a></li>
                    <li class="nav-item mb-2"><a class="nav-link p-0 text-muted" href="#contactus">Contact
                        US</a>
                    </li>
                    <li class="nav-item mb-2"><a class="nav-link p-0 text-muted"
                                                 href="#services">Service</a>
                    </li>
                    <li class="nav-item mb-2"><a class="nav-link p-0 text-muted"
                                                 href="{%url 'appointment-make' %}">Make Appointment</a>
                    </li>
                </ul>
            </div>
            <div class="col offset-1 text-center">
                <ul class="list-unstyled overflow-hidden">
                    <li>Mobile: +291-7111950</li>
                    <li>Tel: +291-1-125252</li>
                    <li>Fax: +291-1-125251</li>
                    <li>Email: alwaditraveleritrea@gmail.com</li>
                    <li>Email: alwaditravelandtour@gmail.com</li>
                </ul>
            </div>
        </div>

        <div class="d-flex justify-content-center border-top mb-2">
            <p>&copy; 2023 Alwadi Travel & Tour. All rights reserved.</p>

        </div>
    </footer>
</div>
</div>
<script src="{% static  'alwaditravel/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static  'alwaditravel/js/jquery.min.js' %}"></script>
<script src="{% static  'alwaditravel/js/jquery-ui.min.js' %}"></script>
{% block script %}
{% endblock%}

</body>


</html>

alwaditravel/templates/alwaditravel/messages.html
{% load static %}
<!-- Messages -->
{%for message in messages%}
{% if message.tags == 'error' %}
<script src="{% static 'alwaditravel/js/sweetalert.min.js' %}"></script>
<script>
        var m = "{{ message|safe }}";
        swal("Error !", m, "error")
    </script>
{% endif %}
{% if message.tags == 'success' %}
<script src="{% static 'alwaditravel/js/sweetalert.min.js' %}"></script>
<script>
        var m = "{{ message|safe }}";
        swal("Perfect !", m, "success")
    </script>
{% endif %}
{% endfor%}